### ISSUE TITLE
error: ‘TRUE’ was not declared in this scope

### ISSUE THREAD

**Issue by LMurphy186232** [edfm-tum/iland-model#2]
When compiling iLand for Linux, I get the following error message:

In file included from ../../src/iland/ui/linkxmlqt.cpp:1:
../../src/iland/ui/linkxmlqt.h:17:5: warning:   when initialized here [-Wreorder]
   17 |     SettingsItem(size_t index, QString akey, QString atype, QString alabel, QString atooltip, QString adefault, QString avisibility, QString aparent = “”, QString aAltLabel = “”):
      |     ^~~~~~~~~~~~
../../src/iland/ui/linkxmlqt.cpp: In member function ‘void LinkXmlQt::readValuesXml(QStackedWidget*)’:
../../src/iland/ui/linkxmlqt.cpp:260:46: error: ‘TRUE’ was not declared in this scope
  260 |                         checkBox->setChecked(TRUE);
      |                                              ^~~~
../../src/iland/ui/linkxmlqt.cpp:263:46: error: ‘FALSE’ was not declared in this scope
  263 |                         checkBox->setChecked(FALSE);

This is when compiling iland, after successful compilation of plugins.

My first thought is that this is a Qt version issue. This is using Qt 6.5.4. Can you please tell me the exact minor version that iLand is currently compiled with, and any other thoughts that you may have on this issue?

**Comment by jonas-kerber** [comment]
I assume you are trying to build the main branch.

I just tried it and the build also failed to build main (on a linux system).
However, I was successful building the "dev" branch using Qt 6.7.2 using this build script (https://iland-model.org/iland-book/Building_iLand.html#building-iland-on-a-standard-linux-server). I did not test for other Qt versions but in my experience you should get errors during `qmake plugins.pro` or `qmake  iland.pro` if your Qt version is too old.

Maybe you could try if that works for you for now (even though dev is a little ahead of main).
I will investigate with @werner-rammer once he is back from vacation what the problems on main are

**Comment by LMurphy186232** [comment]
Update: After making my git clone of iLand, I used "git checkout v2.0" and it compiled with a 6.5.4 version of Qt. Thanks for your reply!

**Comment by LMurphy186232** [comment]
Checking out the proper iLand branch resolves the issue.

**Comment by werner-rammer** [comment]
In addition, the "main" branch includes now the minor fix that caused the problem ([058749f](https://github.com/edfm-tum/iland-model/commit/058749ffb2d174d171ca1fc8541baa0f127babbf))
